apiVersion: v1
kind: Service
metadata:
  name: osticket-service
  labels:
    app: osticket-service
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: osticket-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket-service
spec:
  selector:
    matchLabels:
      app: osticket-service
  replicas: 1
  template:
    metadata:
      labels:
        app: osticket-service
    spec:
      containers:
      - name: osticket-service
        image: osticket/osticket
        ports:
        - containerPort: 80
        env:
        - name: OSTICKET_URL
          valueFrom:
            secretKeyRef:
              name: osticket-details
              key: url
        - name: OSTICKET_API_KEY
          valueFrom:
            secretKeyRef:
              name: osticket-details
              key: api-key
